repos:
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       language_version: python3.12  # Ensure Python 3.12 is used

  - repo: https://github.com/psf/black
    rev: "24.10.0"
    hooks:
      - id: black
        language_version: python3.12  # Ensure Python 3.12 is used

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.9"
    hooks:
      - id: ruff
        language_version: python3.12  # Ensure Python 3.12 is used
        args: ["--fix"]
